name: Windows Build

on: [push]

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DBUILD_SHARED_LIBS=TRUE
    - name: build
      run: cmake --build build --config Release
    - name: test
      run: cd build && ctest
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: build
